# Generated by Django 4.2 on 2023-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='url_img',
            field=models.TextField(default=0, max_length=500, verbose_name='Ссылка на изображение'),
            preserve_default=False,
        ),
    ]
