# Generated by Django 4.2 on 2023-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bloger_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='username',
            field=models.CharField(default=0, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloger',
            name='contacts',
            field=models.TextField(blank=True, max_length=100, verbose_name='Контакты'),
        ),
    ]
