# Generated by Django 4.2 on 2023-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bloger_username_alter_bloger_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='url_inst',
            field=models.TextField(default=0, max_length=500, verbose_name='Ссылка на Instagram'),
            preserve_default=False,
        ),
    ]
