# Generated by Django 4.2 on 2023-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bloger_url_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='slug',
            field=models.SlugField(default=0, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
